require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CoinsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Coin. As you add validations to Coin, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoinsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all coins as @coins" do
      coin = Coin.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:coins)).to eq([coin])
    end
  end

  describe "GET show" do
    it "assigns the requested coin as @coin" do
      coin = Coin.create! valid_attributes
      get :show, {:id => coin.to_param}, valid_session
      expect(assigns(:coin)).to eq(coin)
    end
  end

  describe "GET new" do
    it "assigns a new coin as @coin" do
      get :new, {}, valid_session
      expect(assigns(:coin)).to be_a_new(Coin)
    end
  end

  describe "GET edit" do
    it "assigns the requested coin as @coin" do
      coin = Coin.create! valid_attributes
      get :edit, {:id => coin.to_param}, valid_session
      expect(assigns(:coin)).to eq(coin)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Coin" do
        expect {
          post :create, {:coin => valid_attributes}, valid_session
        }.to change(Coin, :count).by(1)
      end

      it "assigns a newly created coin as @coin" do
        post :create, {:coin => valid_attributes}, valid_session
        expect(assigns(:coin)).to be_a(Coin)
        expect(assigns(:coin)).to be_persisted
      end

      it "redirects to the created coin" do
        post :create, {:coin => valid_attributes}, valid_session
        expect(response).to redirect_to(Coin.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coin as @coin" do
        post :create, {:coin => invalid_attributes}, valid_session
        expect(assigns(:coin)).to be_a_new(Coin)
      end

      it "re-renders the 'new' template" do
        post :create, {:coin => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested coin" do
        coin = Coin.create! valid_attributes
        put :update, {:id => coin.to_param, :coin => new_attributes}, valid_session
        coin.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested coin as @coin" do
        coin = Coin.create! valid_attributes
        put :update, {:id => coin.to_param, :coin => valid_attributes}, valid_session
        expect(assigns(:coin)).to eq(coin)
      end

      it "redirects to the coin" do
        coin = Coin.create! valid_attributes
        put :update, {:id => coin.to_param, :coin => valid_attributes}, valid_session
        expect(response).to redirect_to(coin)
      end
    end

    describe "with invalid params" do
      it "assigns the coin as @coin" do
        coin = Coin.create! valid_attributes
        put :update, {:id => coin.to_param, :coin => invalid_attributes}, valid_session
        expect(assigns(:coin)).to eq(coin)
      end

      it "re-renders the 'edit' template" do
        coin = Coin.create! valid_attributes
        put :update, {:id => coin.to_param, :coin => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coin" do
      coin = Coin.create! valid_attributes
      expect {
        delete :destroy, {:id => coin.to_param}, valid_session
      }.to change(Coin, :count).by(-1)
    end

    it "redirects to the coins list" do
      coin = Coin.create! valid_attributes
      delete :destroy, {:id => coin.to_param}, valid_session
      expect(response).to redirect_to(coins_url)
    end
  end

end
